name: scanner_ocr_module
description: "A complete Scanner + OCR module."
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_document_scanner: ^0.4.0
  google_mlkit_text_recognition: ^0.13.0
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  image: ^4.2.0
  permission_handler: ^11.3.1
  share_plus: ^10.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.6
  provider: ^6.1.2
  google_fonts: ^6.1.0
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  sign_in_button: ^5.0.0
  path_provider: ^2.1.2
  http: ^1.2.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "C:/Users/kaust/.gemini/antigravity-ide/brain/cc57c95f-2aa8-4ce6-bbfe-a1c64a86cb32/mediscan_icon_1782634707187.png"

flutter:
  uses-material-design: true
