// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcW3gnKOsHLm-OkJvThITiE2QIUbtqVoY',
    appId: '1:1066376738841:web:bd64b4bf71979e5de61288',
    messagingSenderId: '1066376738841',
    projectId: 'abha-sync-app',
    authDomain: 'abha-sync-app.firebaseapp.com',
    storageBucket: 'abha-sync-app.firebasestorage.app',
    measurementId: 'G-YRGML1DGNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ACge-d8J9lHSO7EYnIVQGQHLDG6KI88',
    appId: '1:1066376738841:android:84eee7e85450952de61288',
    messagingSenderId: '1066376738841',
    projectId: 'abha-sync-app',
    storageBucket: 'abha-sync-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6oBSv38Jd6Qbaaxca_ghMep11qALOE_A',
    appId: '1:1066376738841:ios:f622c2e13c05e88fe61288',
    messagingSenderId: '1066376738841',
    projectId: 'abha-sync-app',
    storageBucket: 'abha-sync-app.firebasestorage.app',
    iosBundleId: 'com.example.scannerOcrModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6oBSv38Jd6Qbaaxca_ghMep11qALOE_A',
    appId: '1:1066376738841:ios:f622c2e13c05e88fe61288',
    messagingSenderId: '1066376738841',
    projectId: 'abha-sync-app',
    storageBucket: 'abha-sync-app.firebasestorage.app',
    iosBundleId: 'com.example.scannerOcrModule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcW3gnKOsHLm-OkJvThITiE2QIUbtqVoY',
    appId: '1:1066376738841:web:04b629f99eb4ba9ee61288',
    messagingSenderId: '1066376738841',
    projectId: 'abha-sync-app',
    authDomain: 'abha-sync-app.firebaseapp.com',
    storageBucket: 'abha-sync-app.firebasestorage.app',
    measurementId: 'G-RHQB7GENZY',
  );
}
